spring:
  redis:
   host: 127.0.0.1
   port: 6379
   timeout: 5000ms


  datasource:
    url: jdbc:mysql://localhost:3306/redis?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root


#指定Mapper文件的路徑,類路徑下Mapper文件夾中的的所有xml文件
mybatis:
  mapper-locations: classpath:mapper/*.xml


#指定logging級別
logging:
  level:
    com:
      redis_study:
        mapper: debug



server:
  port: 8080